[project]
name = "contact-wrangler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
license = "MIT"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.19.1",
    "psycopg>=3.3.5",
    "sqlalchemy>=2.0.52",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"