"""initial schema

Revision ID: 11482554a7cf
Revises: 
Create Date: 2026-09-03 17:49:34.231386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11482554a7cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_number', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'COMPLETED', name='campaign_status'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('project_number')
    )
    op.create_table('contacts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('email_normalized', sa.String(), sa.Computed('lower(trim(email))', ), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('age_raw', sa.String(), nullable=True),
    sa.Column('age', sa.BigInteger(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender_raw', sa.String(), nullable=True),
    sa.Column('gender_normalized', sa.Enum('MALE', 'FEMALE', 'NON_BINARY', 'PREFER_NOT_TO_SAY', 'SELF_DESCRIBED', name='contact_gender_normalized'), nullable=True),
    sa.Column('ethnicity', sa.String(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('education', sa.String(), nullable=True),
    sa.Column('linkedin', sa.String(), nullable=True),
    sa.Column('facebook', sa.String(), nullable=True),
    sa.Column('twitter', sa.String(), nullable=True),
    sa.Column('other_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('job_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('email_validation', sa.Enum('VALID', 'INVALID', 'UNKNOWN', 'CATCH_ALL', name='email_validation'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_opt_in', sa.Boolean(), nullable=False),
    sa.Column('is_gmail', sa.Boolean(), sa.Computed("lower(email) LIKE '%%@gmail.com'", ), nullable=False),
    sa.Column('email_domain', sa.String(), sa.Computed("split_part(email, '@', 2)", ), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_normalized')
    )
    op.create_table('campaign_quotas',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('dimension', sa.String(), nullable=False),
    sa.Column('dimension_value', sa.String(), nullable=False),
    sa.Column('target_count', sa.BigInteger(), nullable=False),
    sa.Column('message_template', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'dimension', 'dimension_value')
    )
    op.create_table('contact_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('contact_id', sa.BigInteger(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.Enum('CREATED', 'UPDATED', 'ASSIGNED', 'EMAIL_SENT', 'EMAIL_OPENED', 'EMAIL_CLICKED', 'REPLIED', 'BOUNCED', 'UNSUBSCRIBED', name='contact_event_type'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('mailing_strategy', sa.Enum('MAILMERGE', 'SALESFORGE', 'GREENARROW', 'SUPERSEND', name='mailing_strategy'), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contact_events_contact_occurred', 'contact_events', ['contact_id', 'occurred_at'], unique=False)
    op.create_table('campaign_contacts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('contact_id', sa.BigInteger(), nullable=False),
    sa.Column('quota_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'OPENED', 'CLICKED', 'REPLIED', 'BOUNCED', 'UNSUBSCRIBED', 'EXCLUDED', name='assignment_status'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['quota_id'], ['campaign_quotas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'contact_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaign_contacts')
    op.drop_index('ix_contact_events_contact_occurred', table_name='contact_events')
    op.drop_table('contact_events')
    op.drop_table('campaign_quotas')
    op.drop_table('contacts')
    op.drop_table('campaigns')
    sa.Enum(name='mailing_strategy').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='contact_event_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='assignment_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='email_validation').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='contact_gender_normalized').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='campaign_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
