"""add indexes for filtering and eligibility query

Revision ID: 133789490c0b
Revises: acb87d59c7d3
Create Date: 2026-09-03 19:24:49.925628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '133789490c0b'
down_revision: Union[str, Sequence[str], None] = 'acb87d59c7d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_campaign_contacts_contact_last_sent', 'campaign_contacts', ['contact_id', 'last_sent_at'], unique=False)
    op.create_index('ix_campaign_contacts_quota', 'campaign_contacts', ['quota_id'], unique=False)
    op.create_index('ix_contacts_active_validation', 'contacts', ['is_active', 'email_validation'], unique=False)
    op.create_index('ix_contacts_country', 'contacts', ['country'], unique=False)
    op.create_index('ix_contacts_ethnicity', 'contacts', ['ethnicity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contacts_ethnicity', table_name='contacts')
    op.drop_index('ix_contacts_country', table_name='contacts')
    op.drop_index('ix_contacts_active_validation', table_name='contacts')
    op.drop_index('ix_campaign_contacts_quota', table_name='campaign_contacts')
    op.drop_index('ix_campaign_contacts_contact_last_sent', table_name='campaign_contacts')
    # ### end Alembic commands ###
