"""add server-side defaults

Revision ID: acb87d59c7d3
Revises: 11482554a7cf
Create Date: 2026-09-03 18:58:19.599929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'acb87d59c7d3'
down_revision: Union[str, Sequence[str], None] = '11482554a7cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaign_contacts', 'status',
               existing_type=postgresql.ENUM('PENDING', 'SENT', 'OPENED', 'CLICKED', 'REPLIED', 'BOUNCED', 'UNSUBSCRIBED', 'EXCLUDED', name='assignment_status'),
               server_default='PENDING',
               existing_nullable=False)
    op.alter_column('campaigns', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'ACTIVE', 'PAUSED', 'COMPLETED', name='campaign_status'),
               server_default='DRAFT',
               existing_nullable=False)
    op.alter_column('contacts', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('contacts', 'is_opt_in',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'is_opt_in',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('contacts', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('campaigns', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'ACTIVE', 'PAUSED', 'COMPLETED', name='campaign_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('campaign_contacts', 'status',
               existing_type=postgresql.ENUM('PENDING', 'SENT', 'OPENED', 'CLICKED', 'REPLIED', 'BOUNCED', 'UNSUBSCRIBED', 'EXCLUDED', name='assignment_status'),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
