"""add industry index

Revision ID: f3daba32e267
Revises: 72a603fe6339
Create Date: 2026-09-08 23:58:10.592306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3daba32e267'
down_revision: Union[str, Sequence[str], None] = '72a603fe6339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_contacts_industry', 'contacts', ['industry'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contacts_industry', table_name='contacts')
    # ### end Alembic commands ###
